cloudera:
  build: ./cloudera
  hostname: quickstart.cloudera
  command: /app.sh
  tty: true
  privileged: true
 
  ports:
    - "58888:8888"
    - "8000:80" 
    - "7180:7180"
  links:
    - db
db:
  build: ./mysql
  command: mysqld --user=root --verbose
  ports:
    - "3306:3306"
  environment:
    MYSQL_DATABASE: "test"
    MYSQL_USER: "test"
    MYSQL_PASSWORD: "test"
    MYSQL_ROOT_PASSWORD: "root"
    MYSQL_ALLOW_EMPTY_PASSWORD: "yes"